travis:
  secure:
    BINSTAR_TOKEN: jYl+gRM/SRcsVBPaRUvKrl8OguFLcthM1FWS4pwVxmfJAAKLjjp+lfUV/C+yrDjc450+GCQN0roNQe1mu0Vu/vKmYC9/VuPLS3Cquff5ztHrt89HGX40VY6qYHKEswo30icW6TasN6tpACqdbEVQ5fHh/M64/YdyNE3e9RZrNfLPblAY/8aNrT+MSdyArTEpStBPZpHD98Pm7+kk0k3kaxkvcVFzoMReUXz3O4Tb4ahzw5qXyLQ4GmgidHJ8rwZnjpzShPkxGDgBthLIQDEhYUXrSEf5CraG7IvJfh7j0gu6w5thIwRJWP4OXYGmesG81I1DhRRdEcIniwre9vhDlHS8BM5SUw2018Jh76VUyzjUhg1e/s5YaSvFS3FgWjHi3pMz0kpCZdV4cFishM8LX1l30fOnMYkQZU6rjjY2fBN1VXsSBGOf+V8J5sW4CHDs9SefHuQXuuuvsTfy9F6eBaCog98gwUFCyt0dIWphPGx8aAjsbvgKA7IU8uLwnWLwpOvFDLjF4w4qZYbPMpqP6xeH3BVALLiLslGaC82dwdWH8Kof/upRiq3PnHb7pKjB7+lkd38My5gqIpzBOykNE1YRGj7x/cg5cbt4n+i/TDcm245Z4MU/EpzqefHG20xU7TMbQtySvtJNEUnxYnOkDMAn/Pu6qk+mMofa1PijAQE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
